package jcrystal.clients.generics;

import static jcrystal.utils.StringUtils.camelizar;
import static jcrystal.utils.StringUtils.capitalize;

import java.io.File;
import java.lang.reflect.Modifier;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.BiFunction;
import java.util.function.Function;
import java.util.stream.Collectors;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.json.JSONArray;
import org.json.JSONObject;

import jcrystal.clients.AbsClientGenerator;
import jcrystal.clients.ClientGeneratorDescriptor;
import jcrystal.clients.ClientId;
import jcrystal.clients.android.GeneradorEntidad;
import jcrystal.configs.clients.Client;
import jcrystal.configs.clients.IInternalConfig;
import jcrystal.datetime.DateType;
import jcrystal.entity.types.Autogenerated;
import jcrystal.entity.types.LongText;
import jcrystal.json.JsonLevel;
import jcrystal.lang.Language;
import jcrystal.model.server.db.EntityField;
import jcrystal.model.server.db.EntityClass;
import jcrystal.model.web.HttpType;
import jcrystal.model.web.IWServiceEndpoint;
import jcrystal.model.web.JCrystalWebService;
import jcrystal.model.web.JCrystalWebServiceParam;
import jcrystal.reflection.annotations.CrystalDate;
import jcrystal.reflection.annotations.com.jSerializable;
import jcrystal.reflection.annotations.LoginResultClass;
import jcrystal.reflection.annotations.Post;
import jcrystal.reflection.annotations.jEntity;
import jcrystal.reflection.annotations.ws.ContentType;
import jcrystal.reflection.annotations.ws.Method;
import jcrystal.results.Tupla2;
import jcrystal.server.FileDownloadDescriptor;
import jcrystal.service.types.Authorization;
import jcrystal.types.IJType;
import jcrystal.types.JClass;
import jcrystal.types.JEnum.EnumValue;
import jcrystal.types.vars.IAccessor;
import jcrystal.types.JVariable;
import jcrystal.types.utils.GlobalTypes;
import jcrystal.utils.EnviromentMap;
import jcrystal.utils.StringSeparator;
import jcrystal.utils.StringUtils;
import jcrystal.utils.context.CodeGeneratorContext;
import jcrystal.utils.context.CodeGeneratorContext.ContextType;
import jcrystal.utils.langAndPlats.AbsCodeBlock;
import jcrystal.utils.langAndPlats.JavaCode;
import jcrystal.utils.langAndPlats.JavascriptCode;

public class JavaSEClient extends AbsClientGenerator<Client>{

	public final String paqueteEntidades = context.input.SERVER.WEB.getBasePackage()+".entities";
	public final String paqueteValidadores = context.input.SERVER.WEB.getBasePackage()+".validators";
	public final String paqueteResultados = context.input.SERVER.WEB.getBasePackage()+".results";
	public final String paquetePushs = context.input.SERVER.WEB.getBasePackage()+".pushs";
	public final String paqueteUtils = context.input.SERVER.WEB.getBasePackage()+".net.utils";
	public final String paquetePush = context.input.SERVER.WEB.getBasePackage()+".push";
	public final String netPackage = context.input.SERVER.WEB.getBasePackage()+".net"; 
	public final String paqueteControllers =netPackage + ".controllers";
	public final String paquetePadre = context.input.SERVER.WEB.getBasePackage();
	
	public JavaSEClient(ClientGeneratorDescriptor<Client> descriptor){
		super(descriptor);
		List<String> imports = Arrays.asList(paqueteEntidades+".enums.*");
		entityGenerator = new GeneradorEntidad(this, descriptor, paqueteEntidades, "jcrystal", false, imports);
	}
	@Override
	protected void setupEnviroment() throws Exception {
		ContextType.CLIENT.init();
		CodeGeneratorContext.set(Language.JAVA, new JavaTypeConverter(this));
	}
	@Override
	public void generarCliente() throws Exception {
		addResource(paqueteUtils, "RequestError");
		addResource(paqueteUtils, "TipoError");
		addResource(paqueteUtils, "OnErrorListener");
		addResource(paqueteUtils, "OnServerResponse");
		addResource(paqueteUtils, "HTTPUtils");
		addResource(paqueteUtils, "OnVoidSuccessListener");
		addResource("jcrystal", "JSONUtils");
		addResource("jcrystal", "PrintWriterUtils");
		addResource("jcrystal", "ISerializable");
		addResource(netPackage, "NetConfig");
		
		addResource(EnviromentMap.$().$("JCrystalApp", paquetePadre + ".JCrystalApp").$("PACKAGE", netPackage), netPackage, "NetTask");
		
		createUtilFuntions();
		for (int e = 1; e <= 5; e++)
			createListener(e);
		for (IJType c : SUPPORTED_NATIVE_TYPES)
			createListener(c);

		createAbstractNetTasks();
		generarCodigoMobile();
		generarEntidades();
		generarResultados();
		generarEnums();
	}

	private void addResource(Map<String, Object> enviroment, String paquete, String name) throws Exception {
		addResource(JavaSEClient.class.getResourceAsStream("net/" + name), enviroment, paquete.replace(".", File.separator) + File.separator + name + ".java");
	}

	private void addResource(String paquete, String name) throws Exception {
		addResource(JavaSEClient.class.getResourceAsStream("net/" + name), paquete, paquete.replace(".", File.separator) + File.separator + name + ".java");
	}

	private void generarEnums() throws Exception {
		final String paquete = paqueteEntidades + ".enums";
		
		requiredClasses.stream().filter(f->f.isEnum()).forEach(claseEnum->{
			JClass clase = (JClass)claseEnum;
			final JavaCode $ = new JavaCode() {{
				$("package " + paquete + ";");
				$("public enum " + claseEnum.getSimpleName(), () -> {
					for (EnumValue o : clase.enumData.valores)
						$(o.name + "(" + o.propiedades.get("id") + "),");
					
					$(";");
					$("public final int id;");
					$(claseEnum.getSimpleName() + "(int id)", () -> {
						$("this.id = id;");
					});
					clase.enumData.propiedades.forEach((key, type)->{
						if(!key.equals("id"))
							$("public " + $convert(type)+ " "+(key.equals("name")?"getName":key)+"()", ()->{
								$("switch(this)",()->{
									for (EnumValue o : clase.enumData.valores)
										if(type.is(String.class))
											$("case "+ o.name + " : return \"" + o.propiedades.get(key)+"\";");
										else
											$("case "+ o.name + " : return " + o.propiedades.get(key)+";");										
								});
								if(type.is(String.class))
									$("return null;");
								else
									$("return 0;");
							});
					});
					$("public static " + claseEnum.getSimpleName() + " fromId(int id)", () -> {
						$("switch(id)", () -> {
							for (EnumValue o : clase.enumData.valores)
								$("case " + o.propiedades.get("id") + ": return " + o.name + ";");
						});
						$("return null;");
					});
					$("public static <T> T[] mapped(Class<T> clase, "+paqueteUtils+".Function<"+claseEnum.getSimpleName()+", T> mapper)", () -> {
						$("@SuppressWarnings(\"unchecked\")");
						$(claseEnum.getSimpleName()+"[] vals = values();");
						$("final T[] a = (T[]) java.lang.reflect.Array.newInstance(clase, vals.length);");
						$("for(int e = 0; e < a.length; e++)",()->{
							$("a[e] = mapper.eval(vals[e]);");
						});
						$("return a;");
					});
					$("public static <T> T[] mapped(Class<T> clase, "+paqueteUtils+".Predicate<"+claseEnum.getSimpleName()+"> p, "+paqueteUtils+".Function<"+claseEnum.getSimpleName()+", T> mapper)", () -> {
						$("@SuppressWarnings(\"unchecked\")");
						$(claseEnum.getSimpleName()+"[] vals = values();");
						$("int size = 0;");
						$("for(int e = 0; e < vals.length; e++)",()->{
							$("if(p.eval(vals[e]))size++;");
						});
						$("final T[] a = (T[]) java.lang.reflect.Array.newInstance(clase, size);");
						$("for(int e = 0, i = 0; e < vals.length; e++)",()->{
							$("if(p.eval(vals[e]))",()->{
								$("a[i++] = mapper.eval(vals[e]);");								
							});
						});
						$("return a;");
					});
				});
			}};
			exportFile($, paquete.replace(".", File.separator) + File.separator + claseEnum.getSimpleName() + ".java");
		});
		final JavaCode $ = new JavaCode() {{
			$("package " + paquete + ";");
			$("public enum JsonLevel", () -> {
				StringSeparator vals = new StringSeparator(", ");
				for (JsonLevel level : JsonLevel.managedValues)
					vals.add(level.name());
				$(vals + ";");
			});
		}};
		exportFile($, paquete.replace(".", File.separator) + File.separator + "JsonLevel.java");
	}
	private void generarClaseResultadoOPush(String paquete, final JClass clase){
		new JavaCode() {{
			$("package " + paquete + ";");
			$("import java.io.*;");
			$("import static " + paquetePadre + ".JSONUtils.*;");
			$("import " + paqueteEntidades + ".enums.*;");
			
			$("@SuppressWarnings(\"unused\")");
			$("public class " + clase.simpleName + " implements Serializable", () -> {
				clase.attributes.forEach(f->{
					$("private " + $($convert(f.type())) + " " + f.name() + ";");
					$("public " + $($convert(f.type())) + " " + f.name() + "(){return this." + f.name() + ";}");
					$("public void " + f.name() + "(" + $($convert(f.type())) + " val){" + f.name() + " = val;}");
				});
				$("public " + clase.simpleName + "()", () -> {
				});
				$("protected " + clase.simpleName + "(org.json.JSONObject json)throws org.json.JSONException", () -> {
					clase.attributes.forEach(f->{
						if (f.type().isEnum())
							requiredClasses.add(f.type());
						context.utils.extrators.jsonObject.procesarCampo(this, clase, f.accessor().$this());
					});
				});
				generateFromSimpleJson(this, clase, null, clase.attributes);
				generateFromListJson(this, clase, null);
				
				$("//Serializable things");
				$("private void writeObject(ObjectOutputStream aOutputStream) throws IOException", () -> {
					for (final JVariable f : clase.attributes) {
						if (f.type().isPrimitive())
							$("aOutputStream.write" + capitalize(f.type().getSimpleName()) + "(" + f.name() + ");");
						else if (f.type().isEnum())
							$("aOutputStream.writeInt(" + f.name() + "==null?0:" + f.name() + ".id);");
						else if (f.type().is(String.class))
							$("aOutputStream.writeUTF(" + f.name() + ");");
						else
							$("aOutputStream.writeObject(" + f.name() + ");");
					}
				});
				$("private void readObject(ObjectInputStream aInputStream) throws ClassNotFoundException, IOException", () -> {
					for (final JVariable f : clase.attributes) {
						if (f.type().isPrimitive())
							$("this." + f.name() + " = aInputStream.read" + capitalize(f.type().getSimpleName()) + "();");
						else if (f.type().isEnum())
							$("this." + f.name() + " = " + $($convert(f.type())) + ".fromId(aInputStream.readInt());");
						else if (f.type().is(String.class))
							$("this." + f.name() + " = aInputStream.readUTF();");
						else if (f.type().isAnnotationPresent(jSerializable.class))
							$("this." + f.name() + " = ("+f.type().getSimpleName()+")aInputStream.readObject();");
						else
							$("this." + f.name() + " = ("+$($convert(f.type()))+")aInputStream.readObject();");
					}
				});
			});
			exportFile(this, paquete.replace(".", File.separator) + File.separator + clase.getSimpleName() + ".java");
		}};
		new JavaCode() {{
			$("package " + paquete + ";");
			$("import java.io.*;");
			$("import jcrystal.PrintWriterUtils;");
			$("import static jcrystal.JSONUtils.*;");
			$("import " + paqueteEntidades + ".enums.*;");
			$("@SuppressWarnings(\"unused\")");
			$("public class Serializer" + clase.simpleName, () -> {
				context.utils.generadorToJson.generateJsonify(clase, this, null, clase.attributes.stream().map(f ->
					f.accessor().prefix("objeto.").asProperty()
				).collect(Collectors.toList()));
			});
			exportFile(this, paquete.replace(".", File.separator) + File.separator + "Serializer" + clase.getSimpleName() + ".java");
		}};
	}

	public void crearcodigoTokenSeguridad(AbsCodeBlock code, JClass clase) {
		code.new B() {
			{
				$("private static " + clase.simpleName + " cachedToken = null;");
				$("public " + clase.simpleName + " storeToken()throws org.json.JSONException", () -> {
					$("if(DB" + clase.simpleName + ".store(\"Token\", this))cachedToken = this;");
					$("return this;");
				});
				$("public static String getTokenId()", () -> {
					$("if(cachedToken != null)return cachedToken.token;");
					$("else getToken();");
					$("if(cachedToken == null)return null;");
					$("return cachedToken.token;");
				});
				$("public static void deleteToken()", () -> {
					$("cachedToken = null;");
					$("DB" + clase.simpleName + ".delete(\"Token\");");
				});
				$("public static " + clase.simpleName + " getToken()", () -> {
					$("if(cachedToken == null)", () -> {
						$("cachedToken = DB" + clase.simpleName + ".retrieve(\"Token\");");
					});
					$("return cachedToken;");
				});
				$("public static boolean isAuthenticated()", () -> {
					$("return getToken() != null;");
				});
				if (context.data.rolClass != null) {
					for (final EnumValue value : context.data.rolClass.enumData.valores) {
						String name = "Rol" + StringUtils.camelizar(value.name);
						$("public static boolean is" + name + "()", () -> {
							if(!value.propiedades.containsKey("id"))
								throw new NullPointerException("No hay id para el enum de roles: " + context.data.rolClass.name);
							$("return getToken() != null && (cachedToken.rol & " + value.propiedades.get("id") + ")!=0;");
						});
					}
				}
			}
		};
	}

	private void generarResultados() throws Exception {
		requiredClasses.stream().filter(f->f.isAnnotationPresent(jSerializable.class)).forEach(clase->{
			generarClaseResultadoOPush(paqueteResultados, (JClass)clase);
		});
	}
	private void createAbstractNetTasks() throws Exception{
		final String netPackage = paqueteControllers.substring(0, paqueteControllers.lastIndexOf('.'));
		final JavaCode codeEnum = new JavaCode() {{
			$("package " + netPackage + ";");
			$("public enum RequestType", () -> {
				$(Arrays.stream(Method.values()).filter(tipo->tipo != Method.DEFAULT).map(f->f.name()+"("+f.isPostLike()+")").collect(Collectors.joining(", "))+";");
				$("public final boolean isPost;");
				$("RequestType(boolean isPost)",()->{
					$("this.isPost = isPost;");
				});
			});
		}};
		exportFile(codeEnum, netPackage.replace(".", File.separator) + File.separator + "RequestType.java");
		for(IInternalConfig config : descriptor.configs.values()) {
			final String id = config.id()==null?"Default":config.id();
			final JavaCode code = new JavaCode() {{
				$("package " + netPackage + ";");
				$("import "+paqueteUtils+".*;");
				$("public abstract class Abs"+id+"Manager<T> extends NetTask<T>", () -> {
					$("public static boolean DEBUG = false;");
					$("public static final String BASE_URL = \"" + config.BASE_URL(null)+"\";");
					$("private boolean formData;");
					$("protected String boundary;");
					$("public Abs"+id+"Manager(OnErrorListener onError)", () -> {
						$("super(onError);");
					});
					$("@Override protected final T doRequest()throws Exception", () -> {				
						$("String $url = BASE_URL + getUrl();");
						$("java.net.HttpURLConnection connection = (java.net.HttpURLConnection) new java.net.URL($url).openConnection();");
						$if("DEBUG",()->{
							$("System.out.println($url);");
						});
						$("connection.setConnectTimeout(NetConfig.TIMEOUT);");
						$("connection.setRequestMethod(type.name());");
						$("connection.setRequestProperty(\"Accept\", \"application/json\");");
						$("if(authorization != null)",()->{
							$("connection.setRequestProperty(\"Authorization\", authorization);");							
						});
						$("if($headers != null)",()->{
							$("for (java.util.Map.Entry<String, String> entry : $headers.entrySet())",()->{
								$("connection.setRequestProperty(entry.getKey(), entry.getValue());");							
							});
						});
						
						$if("type.isPost",()->{
							$if("formData",()->{
								$("connection.setRequestProperty(\"Content-Type\", \"multipart/form-data; boundary=---------------------------\"+boundary);");
							});
							$else(()->{
								$("connection.setRequestProperty(\"Content-Type\", \"application/json\");");
							});
						});
						$if("type.isPost",()->{
							$("connection.setDoOutput(true);");
						});
						$("connection.connect();");
						$if("type.isPost",()->{
							$if("DEBUG",()->{
								$("java.io.ByteArrayOutputStream $baos = new java.io.ByteArrayOutputStream();");
								$("try(java.io.PrintWriter _pw = new java.io.PrintWriter(new java.io.OutputStreamWriter($baos, \"UTF-8\"), false))",()->{
									$("makeBody(_pw);");
								});
								$("System.out.println(new String($baos.toByteArray()));");
								$("connection.getOutputStream().write($baos.toByteArray());");
							})
							.$else(()->{
								$("try(java.io.PrintWriter _pw = new java.io.PrintWriter(new java.io.OutputStreamWriter(connection.getOutputStream(), \"UTF-8\"), false))",()->{
									$("makeBody(_pw);");
								});
							});
						});

						$("final int responseCode = connection.getResponseCode();");
						$if("DEBUG",()->{
							$("System.out.println(\"responseCode \" + responseCode);");
						});
						$if("responseCode >= 200 && responseCode <= 299", () -> {
							$("final StringBuilder resp = HTTPUtils.readResponse(connection.getInputStream());");
							$("connection.disconnect();");
							$("onPostExecute(getResponse(resp));");
						});
						$else(() -> {
							$if("onError != null", () -> {
								$("final java.io.InputStream errorStream = connection.getErrorStream();");
								$("final StringBuilder resp;");
								$if("errorStream != null",()->{
									$("resp = HTTPUtils.readResponse(errorStream);");
								}).$else(()->{
									$("resp = new StringBuilder(\"\");");
									
								});
								$("connection.disconnect();");
								$("String $error = resp.toString();");
								$if("DEBUG",()->{
									$("System.out.println(\"error \" + $error);");
								});
								$("error = new RequestError(responseCode, $error);");
								$("onPostExecute(null);");
							});
							$else(() -> {
								$("connection.disconnect();");
							});
						});
						$("return null;");
					});
					$("public Abs"+id+"Manager<T> doFormData()",()->{
						$("formData = true;");
						$("boundary = Long.toString(System.currentTimeMillis());");
						$("return this;");
					});
					$("protected void onPostExecute(T result)", () -> {
						$if("result != null", () -> {
							$("try", () -> {
								$("onResponse(result);");
							});
							$("catch(Exception ex)", () -> {
								$("if(onError!=null)onError.onError(new RequestError(TipoError.SERVER_ERROR, \"Ocurrió un error con el servidor\"));");
							});
						});
						$else_if("onError != null", () -> {
							$("onError.onError(error);");
						});
					});
					$("protected void makeBody(java.io.PrintWriter _pw) throws java.io.UnsupportedEncodingException, java.io.IOException", () -> {});
					$("protected abstract void onResponse(T result) throws Exception;");
					$("abstract T getResponse(StringBuilder resp) throws Exception;");
					for(Class<?> tipo : new Class<?>[] {String.class, JSONObject.class, JSONArray.class}) {
						$("public abstract static class "+tipo.getSimpleName()+"Resp extends Abs"+id+"Manager<"+tipo.getName()+">",()->{
							$("public "+tipo.getSimpleName()+"Resp(OnErrorListener onError)",()->{
								$("super(onError);");
							});
							$("@Override protected "+tipo.getName()+" getResponse(StringBuilder resp)throws Exception",()->{
								if (tipo == String.class) {
									$("return resp.toString();");
									return;
								} else if (tipo == JSONArray.class)
									$("org.json.JSONArray json = new org.json.JSONArray(resp.toString());");
								else
									$("org.json.JSONObject json = new org.json.JSONObject(resp.toString());");
	
								if (config.SUCCESS_TYPE() != null) {
									IJType successType = getSuccessType(config.SUCCESS_TYPE());
									if (tipo == JSONArray.class)
										$("final " + $($convert(successType)) + " success = "+config.SUCCESS_DAFAULT_VALUE()+";");
									else
										$("final " + $($convert(successType)) + " success = json.opt" + capitalize($convert(successType).getSimpleName()) + "(\""+config.SUCCESS_NAME()+"\", " + config.SUCCESS_DAFAULT_VALUE() + ");");
								}
								$if(config.SUCCESS_CONDITION(), "return json;");
								if (config.ERROR_CONDITION() != null)
									$if(config.ERROR_CONDITION(), () -> {
										if (tipo == JSONArray.class)
											$("error = new RequestError(0, \"SERVER ERROR\");");
										else
											$("error = new RequestError(json.optInt(\"code\",0), json.getString(\"" + config.ERROR_MESSAGE_NAME() + "\"));");
										$("return null;");
									});
								if (config.UNATHORIZED_CONDITION() != null)
									$if(config.UNATHORIZED_CONDITION(), () -> {
										if (tipo == JSONArray.class)
											$("error = new RequestError(0, \"SERVER ERROR\");");
										else
											$("error = new RequestError(TipoError.UNAUTHORIZED, json.getString(\"" + config.ERROR_MESSAGE_NAME() + "\"));");
										$("return null;");
									});
								if (config.SUCCESS_TYPE() != null) {
									if (tipo == JSONArray.class)
										$("error = new RequestError(0, \"SERVER ERROR\");");
									else
										$("error = new RequestError(TipoError.SERVER_ERROR, json.getString(\"" + config.ERROR_MESSAGE_NAME() + "\"));");
									$("return null;");
								}
							});
						});
					}
				});
			}};
			exportFile(code, netPackage.replace(".", File.separator) + File.separator + "Abs"+id+"Manager.java");
		}
	}

	private void generarCodigoMobile() throws Exception {
		for (final Map.Entry<String, Set<IWServiceEndpoint>> entry : endpoints.entrySet()) {
			String name = "Manager" + StringUtils.capitalize(StringUtils.camelizarSoft(entry.getKey().contains("/") ? entry.getKey().substring(entry.getKey().lastIndexOf('/') + 1) : entry.getKey()));
			final String paquete;
			if (entry.getKey().contains("/"))
				paquete = paqueteControllers + "." + entry.getKey().substring(0, entry.getKey().lastIndexOf('/')).replace("/", ".");
			else
				paquete = paqueteControllers;
			final JavaCode cliente = new JavaCode() {
				{
					$("package " + paquete + ";");
					$("import " + paqueteUtils + ".*;");
					if(context.data.serializableClasses.size()>0)
						$("import " + paqueteResultados + ".*;");
					$("import " + paqueteEntidades + ".*;");
					$("import " + paqueteEntidades + ".enums.*;");
					$("import " + paqueteControllers.substring(0, paqueteControllers.lastIndexOf('.')) + ".*;");
					$("import jcrystal.PrintWriterUtils;");
					$("import static jcrystal.JSONUtils.*;");
					$("public class " + name, () -> {
						for (final IWServiceEndpoint endpoint : entry.getValue()) {
							JCrystalWebService m = (JCrystalWebService)endpoint;
							$("/**");
							$("* " + m.getPath(descriptor));
							$("**/");
							final Tupla2<List<JVariable>, Map<HttpType, List<JVariable>>> clientParams = getParamsWebService(m);
							final List<JVariable> parametros = clientParams.v0;
							if (m.isClientQueueable()) {
								throw new NullPointerException("Error. No se puede tener un WS queueable en JavaSE");
							} else {
								boolean addOnError = true;
								if (m.unwrappedMethod.isVoid)
									parametros.add(P(GlobalTypes.jCrystal.VoidSuccessListener, "onSuccess"));
								else if (m.getReturnType().is(String.class))
									parametros.add(P(GlobalTypes.jCrystal.OnSuccessListener(GlobalTypes.STRING), "onSuccess"));
								else if (SUPPORTED_NATIVE_TYPES.contains(m.getReturnType()))
									parametros.add(P(GlobalTypes.jCrystal.OnSuccessListener(m.getReturnType()), "onSuccess"));
								else if (m.getReturnType().isAnnotationPresent(jSerializable.class))
									parametros.add(P(GlobalTypes.jCrystal.OnSuccessListener($convert(m.getReturnType())), "onSuccess"));
								else if (m.getReturnType().isAnnotationPresent(jEntity.class))
									parametros.add(P(GlobalTypes.jCrystal.OnSuccessListener($convert(m.getReturnType())), "onSuccess"));
								else if (m.getReturnType().isIterable()) {
									parametros.add(P(GlobalTypes.jCrystal.OnSuccessListener($convert(m.getReturnType())), "onSuccess"));
								}else if (m.getReturnType().getSimpleName().startsWith("Tupla")) {
									final List<IJType> tipos = new ArrayList<>();
									for (IJType p : m.getReturnType().getInnerTypes()) {
										if (p.getInnerTypes().isEmpty()) {
											tipos.add($convert(p));
										} else{
											if (p.isSubclassOf(List.class)) {
												IJType subClaseTipo = p.getInnerTypes().get(0);
												tipos.add($convert(subClaseTipo).createListType());
											} else
												throw new NullPointerException("Error, tipos incompatibles. No se puede tener un metodo con retorno " + p);
										}
									}
									parametros.add(P(GlobalTypes.jCrystal.OnSuccessListener(tipos), "onSuccess"));
								}else if(m.unwrappedMethod.returnType.is(FileDownloadDescriptor.class)) {
									addOnError = false;
								}else
									throw new NullPointerException(m.getReturnType().toString());
								if(addOnError)
									parametros.add(P(GlobalTypes.jCrystal.ErrorListener, "onError"));

								IInternalConfig methodConfig = m.exportClientConfig(descriptor);
								
								String methodName = StringUtils.lowercalize(StringUtils.camelizarSoft(m.unwrappedMethod.name()));
								final String visibility = m.isClientQueueable() ? "private" : "public";
								final boolean nativeEmbeddedResponse = methodConfig.embeddedResponse() && SUPPORTED_NATIVE_TYPES.contains(m.getReturnType());
								if(m.getReturnType().is(jcrystal.server.FileDownloadDescriptor.class)) {
									$(visibility + " static String " + methodName + "(" + parametros.stream().map(this::$V).collect(Collectors.joining(", ")) + ")", () -> {
										String ruta = m.getPath(descriptor);
										for (final JCrystalWebServiceParam param : m.parametros)
											if (param.tipoRuta == HttpType.PATH)
												ruta = ruta.replace("$" + param.nombre, "\"+" + param.nombre + "+\"");
										$("String ruta = \"" + ruta + "\";");
										processGetParams(this, clientParams.v1.get(HttpType.GET));
										$("return Abs"+methodConfig.getDefId()+"Manager.BASE_URL + ruta;");
									});
								}else {
									String helperResponseType = (nativeEmbeddedResponse ? "String" : m.isJsonArrayResponse(methodConfig) ? "org.json.JSONArray" : "org.json.JSONObject");
									String helperResponseSimpleType = (nativeEmbeddedResponse ? "String" : m.isJsonArrayResponse(methodConfig) ? "JSONArray" : "JSONObject");
									$(visibility + " static NetTask<"+helperResponseType+"> " + methodName + "(" + parametros.stream().map(this::$V).collect(Collectors.joining(", ")) + ")", () -> {
										parametros.remove(parametros.size()-1);
										String token = m.parametros.stream().filter(f->f.tipoRuta == HttpType.HEADER).map(f->{
											if(f.type().is(Authorization.class))
												return ".authorization("+f.nombre+")";
											else if(f.type().is(ClientId.class))
												return ".header(\""+f.nombre+"\", \""+descriptor.client.id+"\")";
											else if(f.type().is(String.class))
												return ".header(\""+f.nombre+"\", " + f.nombre + ")";
											else
												throw new NullPointerException("Unssuported type  for header : " + f.type());
										}).collect(Collectors.joining());
										token += ".do"+StringUtils.capitalize(m.tipoRuta.name().toLowerCase())+"()";
										token += ".exec()";
										
										$("return new Abs"+methodConfig.getDefId()+"Manager."+helperResponseSimpleType+"Resp(onError)", () -> {
											$("@Override protected String getUrl()throws java.io.UnsupportedEncodingException",()->{
												String ruta = m.getPath(descriptor);
												for (final JCrystalWebServiceParam param : m.parametros)
													if (param.tipoRuta == HttpType.PATH)
														ruta = ruta.replace("$" + param.nombre, "\"+" + param.nombre + "+\"");
												$("String ruta = \"" + ruta + "\";");
												processGetParams(this, clientParams.v1.get(HttpType.GET));
												$("return ruta;");
											});
											$("@Override");
											$("public void onResponse("+helperResponseType+" result)throws Exception",()->{
													if (m.unwrappedMethod.isVoid)
														$("onSuccess.onSuccess();");
													else if (SUPPORTED_NATIVE_TYPES.contains(m.getReturnType())) {
														if (nativeEmbeddedResponse)
															$("onSuccess.onSuccess(" + m.getReturnType().getObjectType().getSimpleName() + ".parse" + StringUtils.capitalize(m.getReturnType().getSimpleName()) + "(result));");
														else
															$("onSuccess.onSuccess(result.get" + StringUtils.capitalize(m.getReturnType().getSimpleName()) + "(\"r\"));");
													} else if (m.getReturnType().isIterable()) {
														final IJType tipoParamero = m.getReturnType().getInnerTypes().get(0);
														if(tipoParamero.isAnnotationPresent(jEntity.class)) {
															$("org.json.JSONArray $array = result.getJSONArray(\"r\");");
															$("java.util.List<" + $convert(tipoParamero) + "> $lista = new java.util.ArrayList<>($array.length());");
															$("for(int pos = 0, l = $array.length(); pos < l; pos++)", () -> {
																$("$lista.add(new " + paqueteEntidades + "." + tipoParamero.getSimpleName() + "($array.getJSONObject(pos), JsonLevel." + m.getJsonLevel(tipoParamero).name() + "));");
															});
															$("onSuccess.onSuccess($lista);");
														} else if (tipoParamero.isAnnotationPresent(jSerializable.class)) {
															requiredClasses.add(tipoParamero);
															if (methodConfig.embeddedResponse()) {
																$("org.json.JSONArray $array = result;");
															} else {
																$("org.json.JSONArray $array = result.getJSONArray(\"r\");");
															}
															$("java.util.List<" + paqueteResultados + "." + tipoParamero.getSimpleName() + "> $lista = new java.util.ArrayList<" + paqueteResultados + "." + tipoParamero.getSimpleName() + ">($array.length());");
															$("for(int pos = 0, l = $array.length(); pos < l; pos++)", () -> {
																$("$lista.add(" + paqueteResultados + "." + tipoParamero.getSimpleName() + ".fromJson($array.getJSONObject(pos)));");
															});
															$("onSuccess.onSuccess($lista);");
														}
													}else if (m.getReturnType().isAnnotationPresent(jEntity.class)) {
														if (methodConfig.embeddedResponse()) {
															if (m.getReturnType().isAnnotationPresent(LoginResultClass.class))
																$("onSuccess.onSuccess(new " + paqueteEntidades + "." + m.getReturnType().getSimpleName() + "(result, JsonLevel." + m.getJsonLevel(m.getReturnType()).name() + ").storeToken());");
															else
																$("onSuccess.onSuccess(new " + paqueteEntidades + "." + m.getReturnType().getSimpleName() + "(result, JsonLevel." + m.getJsonLevel(m.getReturnType()).name() + "));");
														}else if (m.getReturnType().isAnnotationPresent(LoginResultClass.class))
															$("onSuccess.onSuccess(result.isNull(\"r\")?null:new " + paqueteEntidades + "." + m.getReturnType().getSimpleName() + "(result.getJSONObject(\"r\"), JsonLevel." + m.getJsonLevel(m.getReturnType()).name() + ").storeToken());");
														else
															$("onSuccess.onSuccess(result.isNull(\"r\")?null:new " + paqueteEntidades + "." + m.getReturnType().getSimpleName() + "(result.getJSONObject(\"r\"), JsonLevel." + m.getJsonLevel(m.getReturnType()).name() + "));");
													} else if (m.getReturnType().isAnnotationPresent(jSerializable.class)) {
														requiredClasses.add(m.getReturnType());
														 if (methodConfig.embeddedResponse())
															 $("onSuccess.onSuccess(" + paqueteResultados + "." + m.getReturnType().getSimpleName() + ".fromJson(result));");
														 else if (m.getReturnType().isAnnotationPresent(LoginResultClass.class))
															 $("onSuccess.onSuccess(result.isNull(\"r\")?null:" + paqueteResultados + "." + m.getReturnType().getSimpleName() + ".fromJson(result.getJSONObject(\"r\")).storeToken());");
														else
															$("onSuccess.onSuccess(result.isNull(\"r\")?null:" + paqueteResultados + "." + m.getReturnType().getSimpleName() + ".fromJson(result.getJSONObject(\"r\")));");
													} else if (m.getReturnType().getSimpleName().startsWith("Tupla")) {
														final List<IJType> tipos = m.getReturnType().getInnerTypes();
														if (methodConfig.embeddedResponse())
															$("org.json.JSONArray $array = result;");
														else
															$("org.json.JSONArray $array = result.getJSONArray(\"r\");");
														StringSeparator sp = new StringSeparator(',');
														int e = 0;
														for (IJType p : tipos) {
															if (p.getInnerTypes().isEmpty()) {
																if (p.isAnnotationPresent(jEntity.class)) {
																	if(p.isAnnotationPresent(LoginResultClass.class)){
																		sp.add("$array.isNull("+e+")?null:(new " + $($convert(context.data.entidades.targetEntity(p))) + "($array.getJSONObject(" + e + "), JsonLevel." + m.getJsonLevel(p).name() + ").storeToken())");
																	}else {
																		sp.add("$array.isNull("+e+")?null:new " +$($convert(context.data.entidades.targetEntity(p))) + "($array.getJSONObject(" + e + "), JsonLevel." + m.getJsonLevel(p).name() + ")");
																	}
																} else if (p.isAnnotationPresent(jSerializable.class)) {
																	if(p.isAnnotationPresent(LoginResultClass.class)){
																		sp.add("$array.isNull("+e+")?null:("+$convert(p) + ".fromJson($array.getJSONObject(" + e + ")).storeToken())");
																	}else 
																		sp.add("$array.isNull("+e+")?null:"+$convert(p) + ".fromJson($array.getJSONObject(" + e + "))");
																} else if (p.is(Integer.class))
																	sp.add("$array.isNull("+e+")?null:$array.getInt(" + e + ")");
																else if (p.is(Long.class))
																	sp.add("$array.isNull("+e+")?null:$array.getLong(" + e + ")");
																else if (p.is(String.class))
																	sp.add("$array.isNull("+e+")?null:$array.getString(" + e + ")");
																else
																	throw new NullPointerException("Unssuported type " + p);
															} else{
																if (p.isIterable()) {
																	final IJType pClass = p.getInnerTypes().get(0);
																	if (pClass.isAnnotationPresent(jEntity.class)) {
																		sp.add($($convert(context.data.entidades.targetEntity(pClass)))+ ".ListUtils.listFromJson" + m.getJsonLevel(pClass).baseName() + "($array.getJSONArray(" + e + "))");
																	} else if (pClass.isAnnotationPresent(jSerializable.class)) {
																		requiredClasses.add(pClass);
																		sp.add($($convert(pClass)) + ".listFromJson($array.getJSONArray(" + e + "))");
																	} else
																		throw new NullPointerException("Unssuported type " + p);
																} else
																	throw new NullPointerException("Error, tipos incompatibles. No se puede tener un metodo con retorno " + p);
															}
															e++;
														}
														$("onSuccess.onSuccess(" + sp + ");");
													} else
														$("onSuccess.onSuccess(result);");
											});
											if (m.tipoRuta.isPostLike()) {
												if (!m.isMultipart()) {
													List<JCrystalWebServiceParam> bodyParams = m.parametros.stream().filter(param -> param.tipoRuta.isPostLike() && param.nombre.equals("body")).collect(Collectors.toList());
													if (bodyParams.size() > 1)
														throw new NullPointerException("Too many bodys");
													else if (bodyParams.isEmpty())
														context.utils.generadorToJson.generateSimplePlainToJson(Modifier.PROTECTED, "makeBody", $(), this, m.parametros.stream().filter(param -> param.tipoRuta.isPostLike()).map(entityUtils::changeToKeys).collect(Collectors.toList()));
													else {
														
														$("@Override protected void makeBody(java.io.PrintWriter _pw)",()->{
															IAccessor param = entityUtils.changeToKeys(bodyParams.get(0));
															
															if (param.type().is(String.class, org.json.JSONObject.class)) {
																$("_pw.print(" + param.name() + ".toString());");
															} else if (param.type().isPrimitive()) {
																throw new NullPointerException("A " + param.type() + " cant be on body");
															} else if (param.type().isAnnotationPresent(Post.class)) {
																JsonLevel level = param.type().getAnnotation(Post.class).level();
																$("Serializer"+param.type().getSimpleName()+".toJson"+camelizar(level.name())+"(_pw, "+param.name()+");");
															} else if (param.type().isAnnotationPresent(jSerializable.class)) {
																$("Serializer"+param.type().getSimpleName()+".toJson(_pw, "+param.name()+");");
															} else if (param.type().isSubclassOf(List.class)) {
																final IJType tipo = param.type().getInnerTypes().get(0);
																if (tipo.isAnnotationPresent(jSerializable.class)) {
																	$(tipo.getSimpleName() + ".toJson" + tipo.getSimpleName() + "(_pw, " + param.name() + ");");
																} else if (tipo.isAnnotationPresent(Post.class)) {
																	JClass superClase  = context.data.entidades.get(tipo).clase;
																	JsonLevel level = tipo.getAnnotation(Post.class).level();
																	if (param.name().equals("body"))
																		$if(param.name() + " != null", () -> {
																			$(paqueteEntidades + "." + superClase.simpleName + ".toJson" + superClase.simpleName + "(_pw, " + param.name() + ");");
																		});
																} else
																	throw new NullPointerException("Unssuported post type " + param.type().name()); // TODO: Si se postea una lista de Posts o Jsonifies
															} else
																throw new NullPointerException("Unssuported post type " + param.type().name());
														});
													}
												}else {
													$("@Override protected void makeBody(java.io.PrintWriter writer) throws java.io.IOException",()->{
														for (JCrystalWebServiceParam param : m.parametros) 
															if(param.tipoRuta.isPostLike()){
																$if(param.p.type().isPrimitive() ? null : (param.nombre + "!= null"), () -> {
																	onMultipartBoundary(this, param.nombre, ()->{
																		if (param.p.type().isPrimitive()) {
																			$("writer.print(" + param.p.type().getObjectType().name() + ".toString(" + param.nombre + "));");
																		} else if (param.p.type().is(String.class, LongText.class)) {
																			$("writer.print(java.net.URLEncoder.encode(" + param.nombre + ", \"UTF-8\"));");
																		} else if (param.p.type().isPrimitiveObjectType()) {
																			$("writer.print(" + param.p.type().getObjectType().name() + ".toString(" + param.nombre + "));");
																		} else if (param.p.type().isJAnnotationPresent(CrystalDate.class)) {
																			$("writer.print(" + param.nombre + ".format());");
																		} else
																			throw new NullPointerException("Unssuported form data post type " + param.p.type().name());
																	});
																});
															}else if(param.p.type().is("jcrystal.server.FileUploadDescriptor")) {
																$("writer.println(\"-----------------------------\" + boundary);");
																$("writer.append(\"Content-Disposition: form-data; name="+param.name()+"\\r\\n\");");
																$if(param.name()+".mimeType != null",()->{
																	$("writer.append(\"Content-Type: \"+"+param.name()+".mimeType+\"\\r\\n\");");
																});
																$("writer.append(\"\\r\\n\");");
																$("byte[] buffer = new byte[14*1024];");
																$("try",()->{
																	$("java.io.InputStream fis = "+param.name()+".stream != null ? "+param.name()+".stream : new java.io.FileInputStream("+param.name()+".file);");
																	$("for(int n; (n = fis.read(buffer)) != -1; )",()->{
																		$("writer.write(buffer, 0, n);");
																	});
																	$("fis.close();");
																});
																$("catch(java.io.IOException ex)",()->{
																	$("throw ex;");
																});
																$("writer.append(\"\\r\\n\");");
															}
															
														$("writer.println(\"-----------------------------\"+boundary + \"--\");");
													});
												}
											}
										},token+";");
									});
								}
							}
						}
					});
				}
			};
			exportFile(cliente, paquete.replace(".", File.separator) + File.separator + name + ".java");
		}
	}

	private void createUtilFuntions() throws Exception {
		new JavaCode() {{
			$("package " + paqueteUtils + ";");
			$("public interface Predicate<T>", () -> {
				$("public boolean eval(T t);");
			});
			exportFile(this, paqueteUtils.replace(".", File.separator) + File.separator + "Predicate.java");
		}};
		new JavaCode() {{
			$("package " + paqueteUtils + ";");
			$("public interface Function<In, Out>", () -> {
				$("public Out eval(In t);");
			});
			exportFile(this, paqueteUtils.replace(".", File.separator) + File.separator + "Function.java");
		}};
	}
	
	private void createListener(int cantidad) throws Exception {
		final String name = "On" + cantidad + "SuccessListener";

		StringSeparator classParams = new StringSeparator(',');
		final StringSeparator methodParams = new StringSeparator(',');
		for (int e = 0; e < cantidad; e++) {
			String letra = Character.toString((char) ('K' + e));
			classParams.add(letra);
			methodParams.add(letra + " " + letra.toLowerCase());
		}
		final JavaCode cliente = new JavaCode() {
			{
				$("package " + paqueteUtils + ";");
				$("public interface " + name + "<" + classParams + ">", () -> {
					$("public void onSuccess(" + methodParams + ");");
				});
			}
		};
		exportFile(cliente, paqueteUtils.replace(".", File.separator) + File.separator + name + ".java");
	}

	private void createListener(IJType nativetype) throws Exception {
		final String name = "On" + StringUtils.capitalize(nativetype.getSimpleName()) + "SuccessListener";
		final JavaCode cliente = new JavaCode() {
			{
				$("package " + paqueteUtils + ";");
				$("public interface " + name, () -> {
					$("public void onSuccess(" + nativetype.getSimpleName() + " result);");
				});
			}
		};
		exportFile(cliente, paqueteUtils.replace(".", File.separator) + File.separator + name + ".java");
	}
	private void onMultipartBoundary(AbsCodeBlock code, String name, Runnable r) {
		code.$("writer.println(\"-----------------------------\" + boundary);");
		code.$("writer.append(\"Content-Disposition: form-data; name=" + name + "\\r\\n\");");
		code.$("writer.append(\"\\r\\n\");");
		r.run();
		code.$("writer.append(\"\\r\\n\");");
	}
	@Override
	protected <X extends AbsCodeBlock> void processGetParams(X METODO, List<JVariable> params) {
		if(params.isEmpty())
			return;
		METODO.new B() {{
			$("String params = null;");
			for (JVariable param : params) {
				if(param.type().nullable()) {
					$("if(" + param.name() + " != null){");
					METODO.incLevel();
				}
				if (param.type().isPrimitive())
					$("params = (params==null?\"?\":(params + \"&\")) + \"" + param.name() + "=\" + " + param.type().getObjectType().name() + ".toString(" + param.name() + ");");
				else if (param.type().is(String.class))
					$("params = (params==null?\"?\":(params + \"&\")) + \"" + param.name() + "=\" + java.net.URLEncoder.encode(" + param.name() + ", \"UTF-8\");");
				else if (param.type().isPrimitiveObjectType())
					$("params = (params==null?\"?\":(params + \"&\")) + \"" + param.name() + "=\" + " + param.type().getObjectType().name() + ".toString(" + param.name() + ");");
				else if (param.type().isEnum())
					$("params = (params==null?\"?\":(params + \"&\")) + \"" + param.name() + "=\" + " + param.name() + ".id;");
				else if (param.type().getSimpleName().equals("JSONObject"))
					throw new NullPointerException();
				else if (param.type().getSimpleName().equals("JSONArray"))
					throw new NullPointerException();
				else if (param.type().isJAnnotationPresent(CrystalDate.class))
					$("	params = (params==null?\"?\":(params + \"&\")) + \"" + param.name() + "=\" + " + param.name() + ".format();");
				else
					throw new NullPointerException("Parametro no reconocido " + param.type().getSimpleName());
				if(param.type().nullable()) {
					$("}");
					METODO.decLevel();
				}
			}
			$("if(params != null)ruta+=params;");
		}};
	}
	@Override
	protected <X extends AbsCodeBlock> void processPostParams(X METODO, ContentType contentType, List<JVariable> params) {
		throw new NullPointerException("processPostParams");
	}

	public static void generateFromListJson(AbsCodeBlock bloque, final JClass clase, final JsonLevel level) {
		bloque.new B() {
			{
				$("public static java.util.ArrayList<" + clase.getSimpleName() + (level == null ? "" : level.baseName()) + "> listFromJson" + (level == null ? "" : level.baseName()) + "(org.json.JSONArray json)throws org.json.JSONException", () -> {
					$("java.util.ArrayList<" + clase.getSimpleName() + (level == null ? "" : level.baseName()) + "> ret = new java.util.ArrayList<" + clase.getSimpleName() + (level == null ? "" : level.baseName()) + ">(json.length());");
					$("for(int e = 0, i = json.length(); e < i; e++)", () -> {
						$("ret.add(new " + clase.getSimpleName() + "(json.getJSONObject(e)" + (level != null ? ", JsonLevel." + level.name() : "") + "));");
					});
					$("return ret;");
				});
			}
		};
	}

	public void generateFromSimpleJson(AbsCodeBlock bloque, final JClass clase, final JsonLevel level, final List<JVariable> campos) {
		bloque.new B() {
			{
				$("public static " + clase.getSimpleName() + " fromJson" + (level == null ? "" : level.baseName()) + "(org.json.JSONObject json)throws org.json.JSONException", () -> {
					if (level == null)
						$("return new " + clase.getSimpleName() + "(json);");
					else {
						$(clase.getSimpleName() + " ret = new " + clase.getSimpleName() + "();");
						for (final JVariable f : campos)
							context.utils.extrators.jsonObject.procesarCampo(this.P, clase, f.accessor().prefix("ret."));
						$("return ret;");
					}
				});
			}
		};
	}
}
