package jcrystal.annotations.internal.model.db;

import jcrystal.types.JAnnotation;

public class AutogeneratedKey extends JAnnotation{

	private static final long serialVersionUID = 1665511007678621834L;

	public AutogeneratedKey() {
		super(AutogeneratedKey.class);
		// TODO Auto-generated constructor stub
	}

}
