package jcrystal.server.databases;

import java.lang.reflect.Modifier;

import jcrystal.annotations.internal.model.db.AutogeneratedKey;
import jcrystal.configs.server.dbs.DBType;
import jcrystal.model.server.db.EntityClass;
import jcrystal.reflection.annotations.EntityKey;
import jcrystal.types.IJType;
import jcrystal.types.JAnnotation;
import jcrystal.types.JVariable;
import jcrystal.types.utils.GlobalTypes;

public class DBUtils {
	public static IJType getGeneratedKeyType(DBType type) {
		switch (type) {
		case GOOGLE_DATASTORE:
			return GlobalTypes.OBJ_LONG;
		case GOOGLE_FIRESTORE:
			return GlobalTypes.STRING;
		default:
			return null;
		}
	}
	public static JVariable generatedDummyKey(EntityClass owner, DBType type) {
		JVariable id = new JVariable(Modifier.STATIC|Modifier.PRIVATE, getGeneratedKeyType(type), "id");
		if(owner.clase.isAnnotationPresent(EntityKey.class))
			id.addAnnotation(owner.clase.getJAnnotation(EntityKey.class.getName()));
		else
			id.addAnnotation(new JAnnotation(EntityKey.class));
		id.addAnnotation(new AutogeneratedKey());
		return id;
	}
}
