package jcrystal.server.databases.google.firebase.realtimedb;

import java.util.stream.Collectors;

import jcrystal.model.server.db.EntityField;
import jcrystal.server.databases.AbsEntityGenerator;
import jcrystal.server.databases.AbsKeyConverterClass;
import jcrystal.types.utils.GlobalTypes;
import jcrystal.utils.StringUtils;

public class KeyConvertersClass extends AbsKeyConverterClass{

	public KeyConvertersClass(AbsEntityGenerator parent) {
		super(parent);
	}
	@Override
	public String keyType(EntityField f) {
		if(f.keyData == null || f.getTargetEntity() == null)
			return $($convert(f.type())) + " " + f.fieldName();
		else
			return $($convert(f.getTargetEntity().key.getSingleKeyType())) + " " + f.fieldName();
	}
	
	@Override
	public String rawKeyType(EntityField f) {
		if(f.keyData == null || f.getTargetEntity() == null)
			return $($convert(f.type())) + " " + f.fieldName();
		else if(f.getTargetEntity().key.isSimple())
			return $(f.getTargetEntity().key.getSingleKeyType()) + " " + f.fieldName();
		else
			return $(GlobalTypes.ARRAY.STRING) + " " + f.fieldName();
	}
	@Override
	public String entityType(EntityField key) {
		if(key.keyData == null || key.getTargetEntity() == null)
			return $($convert(key.type())) + " " + key.fieldName();
		else
			return $($convert(key.getTargetEntity().clase)) + " " + key.fieldName();
	}
	
	@Override
	public String entityToRawKey(EntityField f) {
		if(f.getTargetEntity() != null) {
			if(f.getTargetEntity().key.isSimple())
				return f.fieldName()+"."+f.getTargetEntity().key.getLlaves().get(0).fieldName()+"()";
			else
				return f.fieldName()+".getRawKey()";
		}
		return f.fieldName();
	}
	@Override
	public String keyToRawKey(EntityField f) {
		if(f.getTargetEntity() != null) {
			if(!f.getTargetEntity().key.isSimple())
				return f.fieldName()+".getRawKey()";
		}
		return f.fieldName();
	}
	
	public String getRawKeyExpresion(String entityName) {
		return getRawKeyExpresion(entityName, parent.entidad.key.size());
	}
	public String getRawKeyExpresion(String entityName, int size) {
		String key = null;
		for(int e = 0; e < size; e++) {
			EntityField f = parent.entidad.key.getLlaves().get(e);
			String accessor = f.fieldName();
			key = key == null ? "" : (key + " + ");
			if(e == parent.entidad.key.getLlaves().size() - 1) {
				if(f.getTargetEntity() != null && f.getTargetEntity().key.isSimple())
					accessor = $(f.getTargetEntity().clase)+".Key.get"+StringUtils.capitalize(f.getTargetEntity().key.getLlaves().get(0).name())+"("+f.fieldName()+")";
				else if(f.isAutogenerated())
					accessor = "(" + accessor + " == null ? \"\" : " + accessor + ")";
				key = key + "\"/\" + " + entityName + " + \"/\" + " + accessor;
			}else if(f.getTargetEntity() != null)
				key = key + accessor;
			else
				key = key + "\"/" + f.dbName + "/\" + " + accessor;
		}
		if(key.startsWith("\"/\" + "))
			return key.substring(6);
		return key;
	}
	public String getEntityKeyToRaw(int size) {
		return parent.entidad.key.stream().limit(size).map(f->{
			if(f.getTargetEntity() != null) {
				if(!f.getTargetEntity().key.isSimple())
					return f.fieldName()+".getRawKey()";
				else
					return $(f.getTargetEntity().clase)+".Key.createRawKey("+f.fieldName()+")";
			}
			return f.fieldName();
		}).collect(Collectors.joining(", "));
	}
}
